project:
  type: website

website:
  site-url: https://www.lindsayjorgenson.com
  title: "Lindsay Jorgenson"
  google-analytics: "G-CHHT2HTHQN"

  sidebar:
    style: "docked"
    search: false
    logo: images/logo.png
    contents:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Gallery"
        href: gallery.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    border: true
    right: "Updated May 20, 2024"


  favicon: images/favicon.png

  google-analytics:
    tracking-id: ""
    anonymize-ip: true

format:
  html:
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html
    theme: [default, my_styles.scss]
    css: styles.css
    mainfont: Jost
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1450px
      margin-width: 0px
      gutter-width: 0px
    include-in-header:
      text: <script type="text/javascript" src="link_content.js"></script>




