project:
  type: website

website:
  site-url: https://www.lindsayjorgenson.com
  title: "Lindsay Jorgenson"

  sidebar:
    style: "docked"
    search: false
    logo: images/logo.png
    contents:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Gallery"
        href: gallery.qmd

  page-footer:
    border: true
    left:
    - icon: github
      href: "https://github.com/lindsayjorgenson"
    - icon: envelope
      aria-label: email
      href: "mailto:lindsaybrookeelliott@gmail.com"
    right:
    - text: Updated May 22, 2024

  favicon: images/favicon.png

  google-analytics:
    tracking-id: "G-CHHT2HTHQN"
    anonymize-ip: true

format:
  html:
    theme: [default, my_styles.scss]
    css: styles.css
    mainfont: Jost
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1450px
      margin-width: 0px
      gutter-width: 0px
    include-in-header:
      text: |
        <script type="text/javascript" src="link_content.js"></script>
        <script type="text/html" src="gtm_code_head.html"></script>
        <script type="text/html" src="gtm_code_body.html"></script>




