::: about-column
```{r}
#| echo: false

library(bsutils)
library(htmltools)
library(bsutils)
```

```{r}
# | echo: false

# carousel
bsutils::carousel(
indicators = TRUE,
controls = FALSE,
class = "carousel-dark",
  bsutils::carouselItem(
    div(
      class = "row",
      div(
        class = "col-lg-4",
        align = "center",
        bslib::card(
          height = 350,
          class = "key-findings-cards",
          bslib::card_header(
            fill = FALSE,
            h2("This is a Key Findings."),
          ),
          bslib::card_body(
            p("This is the text for the Key Finding")
          )
        )
      ),
      div(
        class = "col-lg-4",
        align = "center",
        bslib::card(
          height = 350,
          class = "key-findings-cards",
          bslib::card_header(
            fill = FALSE,
            h2("This is a Key Findings."),
          ),
          bslib::card_body(
            p("This is the text for the Key Finding")
          )
        )
      ),
      div(
        class = "col-lg-4",
        align = "center",
        bslib::card(
          height = 350,
          class = "key-findings-cards",
          bslib::card_header(
            fill = FALSE,
            h2("This is a Key Findings."),
          ),
          bslib::card_body(
            p("This is the text for the Key Finding")
          )
        )
      )
    ),
    interval = 60000L
  )
)
```
:::
